name: tasks
description: Don't forget anything!
version: 1.0.1+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/GoogleSans.ttf